import { DEMO_LISTING_OWNER } from "./demo-owners";
import type { Listing } from "./types";

/** Fictional listings so browse works before anyone posts. Contacts use example.com. */
const sampleListingRows = [
  {
    id: "a1000000-0000-4000-8000-000000000001",
    side: "land",
    title: "48 acres of mixed pasture south of Wooster",
    county: "Wayne",
    nearestTown: "Wooster",
    latitude: 40.78,
    longitude: -81.94,
    landType: "pasture",
    livestockType: "cattle",
    seasons: ["spring", "summer", "fall"],
    availableFrom: "2026-05-01",
    availableUntil: "2026-10-31",
    acres: 48,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "perimeter",
    waterAvailable: true,
    rateNotes: "$1.10 per cow-calf pair per day. Grazier handles daily moves.",
    description:
      "Fescue and clover pasture broken into four paddocks. A pond and a frost-free tank sit on the east line. Looking for a cattle producer who will move animals and leave residual cover, not a season-long set stock.",
    contactName: "Mara Ellison",
    contactEmail: "mara.ellison@example.com",
    contactPhone: "(330) 555-0142",
    createdAt: "2026-08-12T14:00:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000002",
    side: "land",
    title: "Cereal rye after corn, 62 acres near Greenville",
    county: "Darke",
    nearestTown: "Greenville",
    latitude: 40.1,
    longitude: -84.63,
    landType: "cover_crop",
    livestockType: "cattle",
    seasons: ["fall", "winter", "spring"],
    availableFrom: "2026-10-15",
    availableUntil: "2027-04-20",
    acres: 62,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "partial",
    waterAvailable: true,
    rateNotes: "$0.75 per head per day if the grazier handles daily moves.",
    description:
      "Rye drilled after corn silage. One side has a woven-wire line; the rest needs polywire. Water is a hydrant at the lane. Cattle can start once the rye is tall enough to take a bite, usually mid-October, and stay into early spring.",
    contactName: "Dale Horst",
    contactEmail: "dale.horst@example.com",
    contactPhone: "(937) 555-0188",
    createdAt: "2026-08-20T15:10:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000003",
    side: "land",
    title: "Corn residue on 110 acres west of London",
    county: "Madison",
    nearestTown: "London",
    latitude: 39.89,
    longitude: -83.48,
    landType: "crop_residue",
    livestockType: "cattle",
    seasons: ["fall"],
    availableFrom: "2026-09-20",
    availableUntil: "2026-12-15",
    acres: 110,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "none",
    waterAvailable: false,
    rateNotes: "Open to a per-head daily rate or a flat field fee. DEMO · no on-site water — bring a tank.",
    description:
      "Combine finished mid-September. Stalks and some dropped ears. No permanent fence, so the grazier brings polywire and a water tank. Prefer dry cows or stockers that can leave before Christmas.",
    contactName: "Priya Nand",
    contactEmail: "priya.nand@example.com",
    contactPhone: "(740) 555-0164",
    createdAt: "2026-09-02T12:00:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000004",
    side: "land",
    title: "18 acres of oak woods for goat browse",
    county: "Athens",
    nearestTown: "Athens",
    latitude: 39.34,
    longitude: -82.1,
    landType: "woodland",
    livestockType: "goats",
    seasons: ["summer"],
    availableFrom: "2026-06-01",
    availableUntil: "2026-09-30",
    acres: 18,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "partial",
    waterAvailable: true,
    rateNotes: "Brush control is the point. $0.40 per head per day, or a trade.",
    description:
      "South-facing oak woods with honeysuckle and multiflora rose on the edges. A creek runs the west line. Existing fence holds goats on two sides. Looking for a herd that will work the understory without ringing the trees.",
    contactName: "Jonah Hale",
    contactEmail: "jonah.hale@example.com",
    contactPhone: "(740) 555-0119",
    createdAt: "2026-05-18T16:20:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000005",
    side: "land",
    title: "32-acre sheep pasture with interior paddocks",
    county: "Seneca",
    nearestTown: "Tiffin",
    latitude: 41.12,
    longitude: -83.18,
    landType: "pasture",
    livestockType: "sheep",
    seasons: ["summer", "fall"],
    availableFrom: "2026-05-15",
    availableUntil: "2026-09-30",
    acres: 32,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "perimeter",
    waterAvailable: true,
    rateNotes: "$18 per ewe for the season, or a daily rate if the stay is shorter.",
    description:
      "Orchardgrass and clover, five interior paddocks, woven wire around the outside. Water troughs are already in. Guardian-dog friendly. No rams on the place, and the neighbor runs a small cattle herd across the road.",
    contactName: "Ellen Kruse",
    contactEmail: "ellen.kruse@example.com",
    contactPhone: "(419) 555-0173",
    createdAt: "2026-04-28T13:40:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000006",
    side: "land",
    title: "Orchard floor and edge grass, 40 acres",
    county: "Putnam",
    nearestTown: "Ottawa",
    latitude: 41.02,
    longitude: -84.05,
    landType: "other",
    livestockType: "cattle",
    seasons: ["summer", "fall"],
    availableFrom: "2026-08-01",
    availableUntil: "2026-11-15",
    acres: 40,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "none",
    waterAvailable: true,
    rateNotes: "Rate is open. Prefer a grazier who plants nothing and brings fence.",
    description:
      "DEMO · Mixed orchard floor and edge grass — classified as other forage for smoke testing. No perimeter fence. Water from a hydrant on the north headland.",
    contactName: "Chris Baum",
    contactEmail: "chris.baum@example.com",
    contactPhone: "(419) 555-0190",
    createdAt: "2026-07-22T11:05:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000007",
    side: "livestock",
    title: "36 cow-calf pairs looking for winter cover crops",
    county: "Holmes",
    nearestTown: "Millersburg",
    latitude: 40.55,
    longitude: -81.92,
    landType: "cover_crop",
    livestockType: "cattle",
    seasons: ["fall", "winter"],
    availableFrom: "2026-11-01",
    availableUntil: "2027-03-31",
    acres: null,
    headCount: 36,
    travelRadiusMiles: 40,
    fencing: null,
    waterAvailable: null,
    rateNotes: "We can pay a daily per-pair rate and split seed cost on rye.",
    description:
      "Angus-cross pairs. We move cattle daily, haul our own polywire, and can set portable tanks if the field has a hydrant. Home place is south of Millersburg. Looking for cereal rye or a mixed cover within about 40 miles, November through March.",
    contactName: "Ruth Miller",
    contactEmail: "ruth.miller@example.com",
    contactPhone: "(330) 555-0133",
    createdAt: "2026-09-08T18:00:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000008",
    side: "livestock",
    title: "90 ewes need spring forage near Circleville",
    county: "Pickaway",
    nearestTown: "Circleville",
    latitude: 39.6,
    longitude: -82.95,
    landType: "pasture",
    livestockType: "sheep",
    seasons: ["spring"],
    availableFrom: "2027-03-20",
    availableUntil: "2027-06-10",
    acres: null,
    headCount: 90,
    travelRadiusMiles: 30,
    fencing: null,
    waterAvailable: null,
    rateNotes: "Happy to pay by the ewe or by the day. We supply net fence.",
    description:
      "Commercial ewes, lambs already off. We need grass from late March until breeding pastures at home recover. Will travel about 30 miles from Circleville. Electronet and a guardian dog come with the flock. Prefer a field with water and no loose dogs.",
    contactName: "Owen Brant",
    contactEmail: "owen.brant@example.com",
    contactPhone: "(740) 555-0155",
    createdAt: "2026-09-10T09:30:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000009",
    side: "livestock",
    title: "Heritage hogs for woodland browse",
    county: "Brown",
    nearestTown: "Georgetown",
    latitude: 38.87,
    longitude: -83.9,
    landType: "woodland",
    livestockType: "other",
    seasons: ["summer", "fall"],
    availableFrom: "2026-06-01",
    availableUntil: "2026-09-30",
    acres: null,
    headCount: 22,
    travelRadiusMiles: 45,
    fencing: null,
    waterAvailable: null,
    rateNotes: "Brush work can offset part of the grazing fee.",
    description:
      "DEMO · Other livestock type for smoke tests: small heritage hog group suited to woodland edges and mast. Based in Georgetown and willing to drive about 45 miles.",
    contactName: "Lila Crowe",
    contactEmail: "lila.crowe@example.com",
    contactPhone: "(937) 555-0127",
    createdAt: "2026-09-14T20:15:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000010",
    side: "livestock",
    title: "Mixed cattle and sheep need summer grass",
    county: "Knox",
    nearestTown: "Mount Vernon",
    latitude: 40.39,
    longitude: -82.49,
    landType: "pasture",
    livestockType: "mixed",
    seasons: ["spring", "summer", "fall"],
    availableFrom: "2026-05-01",
    availableUntil: "2026-10-15",
    acres: null,
    headCount: 28,
    travelRadiusMiles: 25,
    fencing: null,
    waterAvailable: null,
    rateNotes: "Daily mixed-herd rate is fine. We check animals daily.",
    description:
      "DEMO · Mixed herd for filter smoke tests: a few dry cows with a small ewe flock. Looking for pasture with water within about 25 miles of Mount Vernon.",
    contactName: "Sam Yeager",
    contactEmail: "sam.yeager@example.com",
    contactPhone: "(740) 555-0108",
    createdAt: "2026-09-16T13:00:00.000Z",
  },
] satisfies Array<Omit<Listing, "state" | "ownerId" | "organicCertified" | "organicCertifier" | "isDemo">>;

const valleyListingRows = [
  {
    id: "a1000000-0000-4000-8000-000000000011",
    side: "land",
    state: "Pennsylvania",
    title: "64 acres of grass east of New Holland",
    county: "Lancaster",
    nearestTown: "New Holland",
    latitude: 40.1,
    longitude: -76.09,
    landType: "pasture",
    livestockType: "cattle",
    seasons: ["spring", "summer", "fall"],
    availableFrom: "2026-05-01",
    availableUntil: "2026-10-20",
    acres: 64,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "perimeter",
    waterAvailable: true,
    rateNotes: "$1.00 per pair per day. Daily moves preferred.",
    description:
      "Orchardgrass and clover on rolling ground, already split into six paddocks. A spring-fed tank sits in the middle paddock. Looking for a cattle grazier who will leave residual and be off before we stockpile the last growth.",
    contactName: "Hannah Stoltzfus",
    contactEmail: "hannah.stoltzfus@example.com",
    contactPhone: "(717) 555-0144",
    createdAt: "2026-09-01T15:00:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000012",
    side: "land",
    state: "Pennsylvania",
    title: "Rye and triticale after corn near Williamsport",
    county: "Lycoming",
    nearestTown: "Williamsport",
    latitude: 41.25,
    longitude: -77.02,
    landType: "cover_crop",
    livestockType: "cattle",
    seasons: ["fall", "winter"],
    availableFrom: "2026-10-20",
    availableUntil: "2027-03-15",
    acres: 80,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "none",
    waterAvailable: true,
    rateNotes: "Open to a daily head rate. Grazier brings fence.",
    description:
      "Cover drilled the week after silage chop. No perimeter fence. A hydrant is at the farm lane, and the field drains to a grassed waterway we want left alone. Cattle can start once the stand can take a bite and should be gone before spring tillage.",
    contactName: "Paul Eberly",
    contactEmail: "paul.eberly@example.com",
    contactPhone: "(570) 555-0182",
    createdAt: "2026-09-03T14:20:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000013",
    side: "livestock",
    state: "Pennsylvania",
    title: "28 cow-calf pairs based near Bellefonte",
    county: "Centre",
    nearestTown: "Bellefonte",
    latitude: 40.91,
    longitude: -77.78,
    landType: "pasture",
    livestockType: "cattle",
    seasons: ["summer", "fall"],
    availableFrom: "2026-06-15",
    availableUntil: "2026-10-31",
    acres: null,
    headCount: 28,
    travelRadiusMiles: 50,
    fencing: null,
    waterAvailable: null,
    rateNotes: "We pay a daily per-pair rate and handle the moves.",
    description:
      "Angus-cross pairs. We haul polywire and can set a portable tank if there is a hydrant. Home place is west of Bellefonte. Looking for pasture or a summer annual within about 50 miles, June through October.",
    contactName: "Nora Kephart",
    contactEmail: "nora.kephart@example.com",
    contactPhone: "(814) 555-0160",
    createdAt: "2026-09-04T16:10:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000014",
    side: "livestock",
    state: "Pennsylvania",
    title: "70 ewes looking for spring grass in Bradford County",
    county: "Bradford",
    nearestTown: "Towanda",
    latitude: 41.74,
    longitude: -76.44,
    landType: "pasture",
    livestockType: "sheep",
    seasons: ["spring"],
    availableFrom: "2027-04-10",
    availableUntil: "2027-06-15",
    acres: null,
    headCount: 70,
    travelRadiusMiles: 35,
    fencing: null,
    waterAvailable: null,
    rateNotes: "By the ewe or by the day. We bring electronet.",
    description:
      "Commercial ewes, lambs already weaned by the time we would move. Need a field with water from mid-April until our hill pasture recovers. Guardian dog comes with the flock. Based in Towanda and willing to drive about 35 miles.",
    contactName: "Edith Warren",
    contactEmail: "edith.warren@example.com",
    contactPhone: "(570) 555-0116",
    createdAt: "2026-09-06T12:40:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000015",
    side: "land",
    state: "Kentucky",
    title: "40-acre horse pasture outside Paris",
    county: "Bourbon",
    nearestTown: "Paris",
    latitude: 38.22,
    longitude: -84.24,
    landType: "pasture",
    livestockType: "horses",
    seasons: ["spring", "summer", "fall"],
    availableFrom: "2026-04-15",
    availableUntil: "2026-10-31",
    acres: 40,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "perimeter",
    waterAvailable: true,
    rateNotes: "Monthly rate. We'd like the field rested in July if it burns up.",
    description:
      "Fenced bluegrass and fescue with a run-in shed and two automatic waterers. Shade along the creek. Suitable for a small horse herd that will not overgraze the slopes. No stallions.",
    contactName: "Claire Bowman",
    contactEmail: "claire.bowman@example.com",
    contactPhone: "(859) 555-0194",
    createdAt: "2026-08-28T13:15:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000016",
    side: "land",
    state: "Kentucky",
    title: "Corn stalks on 150 acres south of Hopkinsville",
    county: "Christian",
    nearestTown: "Hopkinsville",
    latitude: 36.8,
    longitude: -87.49,
    landType: "crop_residue",
    livestockType: "cattle",
    seasons: ["fall", "winter"],
    availableFrom: "2026-10-01",
    availableUntil: "2027-01-31",
    acres: 150,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "none",
    waterAvailable: true,
    rateNotes: "Flat field fee or a per-head day rate. Either works.",
    description:
      "Harvest should finish late September. Stalks, some dropped grain, and a rye cover on half the field. No fence. Water is a hydrant at the grain bins. Prefer stockers that can leave before we spray in February.",
    contactName: "Marcus Pettit",
    contactEmail: "marcus.pettit@example.com",
    contactPhone: "(270) 555-0177",
    createdAt: "2026-09-07T17:05:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000017",
    side: "livestock",
    state: "Kentucky",
    title: "40 stockers seeking winter annuals near Glasgow",
    county: "Barren",
    nearestTown: "Glasgow",
    latitude: 36.99,
    longitude: -85.91,
    landType: "cover_crop",
    livestockType: "cattle",
    seasons: ["fall", "winter"],
    availableFrom: "2026-11-01",
    availableUntil: "2027-03-01",
    acres: null,
    headCount: 40,
    travelRadiusMiles: 45,
    fencing: null,
    waterAvailable: null,
    rateNotes: "We can pay daily and split the seed if the field still needs planting.",
    description:
      "Black yearlings, used to a daily move. We bring polywire and a water tank. Looking for cereal rye, triticale, or a mixed cover within about 45 miles of Glasgow, November through February.",
    contactName: "June Harlow",
    contactEmail: "june.harlow@example.com",
    contactPhone: "(270) 555-0138",
    createdAt: "2026-09-09T11:25:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000018",
    side: "livestock",
    state: "Kentucky",
    title: "16 meat goats for brush near Campton",
    county: "Wolfe",
    nearestTown: "Campton",
    latitude: 37.73,
    longitude: -83.55,
    landType: "woodland",
    livestockType: "goats",
    seasons: ["summer", "fall"],
    availableFrom: "2026-06-01",
    availableUntil: "2026-09-15",
    acres: null,
    headCount: 16,
    travelRadiusMiles: 40,
    fencing: null,
    waterAvailable: null,
    rateNotes: "Brush control can count toward the fee.",
    description:
      "Kiko does, good on multiflora and honeysuckle. We haul portable panels and can stay through early September if the browse holds. Based in Campton and willing to drive about 40 miles.",
    contactName: "Eli Combs",
    contactEmail: "eli.combs@example.com",
    contactPhone: "(606) 555-0121",
    createdAt: "2026-09-11T19:00:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000019",
    side: "land",
    state: "West Virginia",
    title: "55 acres of hill pasture near Lewisburg",
    county: "Greenbrier",
    nearestTown: "Lewisburg",
    latitude: 37.8,
    longitude: -80.45,
    landType: "pasture",
    livestockType: "cattle",
    seasons: ["spring", "summer", "fall"],
    availableFrom: "2026-05-10",
    availableUntil: "2026-10-15",
    acres: 55,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "partial",
    waterAvailable: true,
    rateNotes: "$0.90 per pair per day if the grazier moves them.",
    description:
      "Fescue and clover on a south slope, with a spring at the bottom fence. Two sides are woven wire; the ridge needs polywire. Looking for cattle that will be moved, not set-stocked, and off before we stockpile October growth.",
    contactName: "Ruth Alderson",
    contactEmail: "ruth.alderson@example.com",
    contactPhone: "(304) 555-0159",
    createdAt: "2026-08-30T14:45:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000020",
    side: "land",
    state: "West Virginia",
    title: "22 acres of woods and edge for goat browse",
    county: "Preston",
    nearestTown: "Kingwood",
    latitude: 39.47,
    longitude: -79.68,
    landType: "woodland",
    livestockType: "goats",
    seasons: ["summer"],
    availableFrom: "2026-06-15",
    availableUntil: "2026-08-31",
    acres: 22,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "partial",
    waterAvailable: true,
    rateNotes: "The browse work matters more than the check. Rate is negotiable.",
    description:
      "Mixed hardwoods with autumn olive and multiflora on the old field edge. A creek crosses the lower corner. Fence holds on the road side. Looking for goats that will open the understory without barking the crop trees.",
    contactName: "Ben Tasker",
    contactEmail: "ben.tasker@example.com",
    contactPhone: "(304) 555-0186",
    createdAt: "2026-09-05T10:30:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000021",
    side: "livestock",
    state: "West Virginia",
    title: "18 pairs looking for river-bottom grass",
    county: "Kanawha",
    nearestTown: "Charleston",
    latitude: 38.35,
    longitude: -81.63,
    landType: "pasture",
    livestockType: "cattle",
    seasons: ["summer", "fall"],
    availableFrom: "2026-06-01",
    availableUntil: "2026-09-30",
    acres: null,
    headCount: 18,
    travelRadiusMiles: 40,
    fencing: null,
    waterAvailable: null,
    rateNotes: "Daily per-pair rate. We move the herd and check water.",
    description:
      "Crossbred pairs, quiet, used to polywire. Home place is west of Charleston. Looking for pasture with water within about 40 miles, June through September. We can start on a cover crop if the grass is short.",
    contactName: "Ivy Mullins",
    contactEmail: "ivy.mullins@example.com",
    contactPhone: "(304) 555-0148",
    createdAt: "2026-09-12T15:50:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000022",
    side: "livestock",
    state: "West Virginia",
    title: "45 ewes need fall forage near Romney",
    county: "Hampshire",
    nearestTown: "Romney",
    latitude: 39.34,
    longitude: -78.76,
    landType: "pasture",
    livestockType: "sheep",
    seasons: ["fall"],
    availableFrom: "2026-09-15",
    availableUntil: "2026-11-30",
    acres: null,
    headCount: 45,
    travelRadiusMiles: 30,
    fencing: null,
    waterAvailable: null,
    rateNotes: "We pay by the day and bring net fence and a guardian dog.",
    description:
      "White-faced ewes coming off summer pasture. Need grass or a cover crop from mid-September until Thanksgiving, within about 30 miles of Romney. Prefer a field that is not next to a busy road.",
    contactName: "Carl Biser",
    contactEmail: "carl.biser@example.com",
    contactPhone: "(304) 555-0104",
    createdAt: "2026-09-15T18:20:00.000Z",
  },
] satisfies Array<Omit<Listing, "ownerId" | "organicCertified" | "organicCertifier" | "isDemo">>;

const ORGANIC_SAMPLE: Record<string, string> = {
  "a1000000-0000-4000-8000-000000000001": "oeffa",
  "a1000000-0000-4000-8000-000000000007": "oeffa",
  "a1000000-0000-4000-8000-000000000011": "pco",
  "a1000000-0000-4000-8000-000000000015": "kda",
};

export const sampleListings: Listing[] = [
  ...sampleListingRows.map((listing) => ({
    ...listing,
    state: "Ohio" as const,
    ownerId: DEMO_LISTING_OWNER[listing.id] ?? null,
    organicCertified: listing.id in ORGANIC_SAMPLE,
    organicCertifier: ORGANIC_SAMPLE[listing.id] ?? null,
    isDemo: true,
  })),
  ...valleyListingRows.map((listing) => ({
    ...listing,
    ownerId: DEMO_LISTING_OWNER[listing.id] ?? null,
    organicCertified: listing.id in ORGANIC_SAMPLE,
    organicCertifier: ORGANIC_SAMPLE[listing.id] ?? null,
    isDemo: true,
  })),
];
