import type { Listing } from "./types";

/** Fictional Ohio listings so browse works before anyone posts. Contacts use example.com. */
export const sampleListings: Listing[] = [
  {
    id: "a1000000-0000-4000-8000-000000000001",
    side: "land",
    title: "48 acres of mixed pasture south of Wooster",
    county: "Wayne",
    nearestTown: "Wooster",
    latitude: 40.78,
    longitude: -81.94,
    landType: "pasture",
    livestockType: "cattle",
    seasons: ["spring", "summer", "fall"],
    availableFrom: "2026-05-01",
    availableUntil: "2026-10-31",
    acres: 48,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "perimeter",
    waterAvailable: true,
    rateNotes: "$1.10 per cow-calf pair per day. Grazier handles daily moves.",
    description:
      "Fescue and clover pasture broken into four paddocks. A pond and a frost-free tank sit on the east line. Looking for a cattle producer who will move animals and leave residual cover, not a season-long set stock.",
    contactName: "Mara Ellison",
    contactEmail: "mara.ellison@example.com",
    contactPhone: "(330) 555-0142",
    createdAt: "2026-08-12T14:00:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000002",
    side: "land",
    title: "Cereal rye after corn, 62 acres near Greenville",
    county: "Darke",
    nearestTown: "Greenville",
    latitude: 40.1,
    longitude: -84.63,
    landType: "cover_crop",
    livestockType: "cattle",
    seasons: ["fall", "winter", "spring"],
    availableFrom: "2026-10-15",
    availableUntil: "2027-04-20",
    acres: 62,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "partial",
    waterAvailable: true,
    rateNotes: "$0.75 per head per day if the grazier handles daily moves.",
    description:
      "Rye drilled after corn silage. One side has a woven-wire line; the rest needs polywire. Water is a hydrant at the lane. Cattle can start once the rye is tall enough to take a bite, usually mid-October, and stay into early spring.",
    contactName: "Dale Horst",
    contactEmail: "dale.horst@example.com",
    contactPhone: "(937) 555-0188",
    createdAt: "2026-08-20T15:10:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000003",
    side: "land",
    title: "Corn residue on 110 acres west of London",
    county: "Madison",
    nearestTown: "London",
    latitude: 39.89,
    longitude: -83.48,
    landType: "crop_residue",
    livestockType: "cattle",
    seasons: ["fall"],
    availableFrom: "2026-09-20",
    availableUntil: "2026-12-15",
    acres: 110,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "none",
    waterAvailable: true,
    rateNotes: "Open to a per-head daily rate or a flat field fee.",
    description:
      "Combine finished mid-September. Stalks and some dropped ears. No permanent fence, so the grazier brings polywire and a water tank. A hydrant is at the field edge. Prefer dry cows or stockers that can leave before Christmas.",
    contactName: "Priya Nand",
    contactEmail: "priya.nand@example.com",
    contactPhone: "(740) 555-0164",
    createdAt: "2026-09-02T12:00:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000004",
    side: "land",
    title: "18 acres of oak woods for goat browse",
    county: "Athens",
    nearestTown: "Athens",
    latitude: 39.34,
    longitude: -82.1,
    landType: "woodland",
    livestockType: "goats",
    seasons: ["summer"],
    availableFrom: "2026-06-01",
    availableUntil: "2026-09-30",
    acres: 18,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "partial",
    waterAvailable: true,
    rateNotes: "Brush control is the point. $0.40 per head per day, or a trade.",
    description:
      "South-facing oak woods with honeysuckle and multiflora rose on the edges. A creek runs the west line. Existing fence holds goats on two sides. Looking for a herd that will work the understory without ringing the trees.",
    contactName: "Jonah Hale",
    contactEmail: "jonah.hale@example.com",
    contactPhone: "(740) 555-0119",
    createdAt: "2026-05-18T16:20:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000005",
    side: "land",
    title: "32-acre sheep pasture with interior paddocks",
    county: "Seneca",
    nearestTown: "Tiffin",
    latitude: 41.12,
    longitude: -83.18,
    landType: "pasture",
    livestockType: "sheep",
    seasons: ["summer", "fall"],
    availableFrom: "2026-05-15",
    availableUntil: "2026-09-30",
    acres: 32,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "perimeter",
    waterAvailable: true,
    rateNotes: "$18 per ewe for the season, or a daily rate if the stay is shorter.",
    description:
      "Orchardgrass and clover, five interior paddocks, woven wire around the outside. Water troughs are already in. Guardian-dog friendly. No rams on the place, and the neighbor runs a small cattle herd across the road.",
    contactName: "Ellen Kruse",
    contactEmail: "ellen.kruse@example.com",
    contactPhone: "(419) 555-0173",
    createdAt: "2026-04-28T13:40:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000006",
    side: "land",
    title: "Summer annuals after wheat, 40 acres",
    county: "Putnam",
    nearestTown: "Ottawa",
    latitude: 41.02,
    longitude: -84.05,
    landType: "cover_crop",
    livestockType: "cattle",
    seasons: ["summer", "fall"],
    availableFrom: "2026-08-01",
    availableUntil: "2026-11-15",
    acres: 40,
    headCount: null,
    travelRadiusMiles: null,
    fencing: "none",
    waterAvailable: true,
    rateNotes: "Rate is open. Prefer a grazier who plants nothing and brings fence.",
    description:
      "Sorghum-sudangrass and cowpeas seeded after wheat. Ready for cattle in August and still holding in September. No perimeter fence. Water from a hydrant on the north headland. Need the field clear before we put wheat back in.",
    contactName: "Chris Baum",
    contactEmail: "chris.baum@example.com",
    contactPhone: "(419) 555-0190",
    createdAt: "2026-07-22T11:05:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000007",
    side: "livestock",
    title: "36 cow-calf pairs looking for winter cover crops",
    county: "Holmes",
    nearestTown: "Millersburg",
    latitude: 40.55,
    longitude: -81.92,
    landType: "cover_crop",
    livestockType: "cattle",
    seasons: ["fall", "winter"],
    availableFrom: "2026-11-01",
    availableUntil: "2027-03-31",
    acres: null,
    headCount: 36,
    travelRadiusMiles: 40,
    fencing: null,
    waterAvailable: null,
    rateNotes: "We can pay a daily per-pair rate and split seed cost on rye.",
    description:
      "Angus-cross pairs. We move cattle daily, haul our own polywire, and can set portable tanks if the field has a hydrant. Home place is south of Millersburg. Looking for cereal rye or a mixed cover within about 40 miles, November through March.",
    contactName: "Ruth Miller",
    contactEmail: "ruth.miller@example.com",
    contactPhone: "(330) 555-0133",
    createdAt: "2026-09-08T18:00:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000008",
    side: "livestock",
    title: "90 ewes need spring forage near Circleville",
    county: "Pickaway",
    nearestTown: "Circleville",
    latitude: 39.6,
    longitude: -82.95,
    landType: "pasture",
    livestockType: "sheep",
    seasons: ["spring"],
    availableFrom: "2027-03-20",
    availableUntil: "2027-06-10",
    acres: null,
    headCount: 90,
    travelRadiusMiles: 30,
    fencing: null,
    waterAvailable: null,
    rateNotes: "Happy to pay by the ewe or by the day. We supply net fence.",
    description:
      "Commercial ewes, lambs already off. We need grass from late March until breeding pastures at home recover. Will travel about 30 miles from Circleville. Electronet and a guardian dog come with the flock. Prefer a field with water and no loose dogs.",
    contactName: "Owen Brant",
    contactEmail: "owen.brant@example.com",
    contactPhone: "(740) 555-0155",
    createdAt: "2026-09-10T09:30:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000009",
    side: "livestock",
    title: "22 meat goats for woodland or rough pasture",
    county: "Brown",
    nearestTown: "Georgetown",
    latitude: 38.87,
    longitude: -83.9,
    landType: "woodland",
    livestockType: "goats",
    seasons: ["summer", "fall"],
    availableFrom: "2026-06-01",
    availableUntil: "2026-09-30",
    acres: null,
    headCount: 22,
    travelRadiusMiles: 45,
    fencing: null,
    waterAvailable: null,
    rateNotes: "Brush work can offset part of the grazing fee.",
    description:
      "Kiko-cross does and kids. Good on honeysuckle, multiflora, and cedar edges. We haul portable panels and can stay through September if late browse is still there. Based in Georgetown and willing to drive about 45 miles.",
    contactName: "Lila Crowe",
    contactEmail: "lila.crowe@example.com",
    contactPhone: "(937) 555-0127",
    createdAt: "2026-09-14T20:15:00.000Z",
  },
  {
    id: "a1000000-0000-4000-8000-000000000010",
    side: "livestock",
    title: "8 horses need summer pasture in Knox County",
    county: "Knox",
    nearestTown: "Mount Vernon",
    latitude: 40.39,
    longitude: -82.49,
    landType: "pasture",
    livestockType: "horses",
    seasons: ["spring", "summer", "fall"],
    availableFrom: "2026-05-01",
    availableUntil: "2026-10-15",
    acres: null,
    headCount: 8,
    travelRadiusMiles: 25,
    fencing: null,
    waterAvailable: null,
    rateNotes: "Monthly board-style rate is fine. We check animals daily.",
    description:
      "Eight mature riding horses, easy keepers. Looking for shade, water, and a field that is not next to a busy road. We can bring portable fencing if the perimeter is weak. Stay is May through mid-October, within 25 miles of Mount Vernon.",
    contactName: "Sam Yeager",
    contactEmail: "sam.yeager@example.com",
    contactPhone: "(740) 555-0108",
    createdAt: "2026-09-16T13:00:00.000Z",
  },
];
